language: python

python:
    - 3.6-dev

before_install:
    - sudo apt -y install spatialindex libspatialindex-dev

install:
    - pip install --upgrade setuptools pip pytest
    - pip install nbconvert jupyter_client geopandas rtree descartes

script:
    - jupyter nbconvert --to notebook --execute GeoPandas_demo.ipynb
