language: python

python:
    - 3.6-dev

before_install:
    - sudo apt update -y
    - sudo apt -y install libspatialindex-dev

install:
    - pip install --upgrade setuptools pip pytest
    - pip install -r requirements.txt -r requirements-dev.txt

script:
    - jupyter nbconvert --to notebook --execute GeoPandas_demo.ipynb
    - py.test --nbval-lax GeoPandas_demo.nbconvert.ipynb
